version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-node_modules-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-node_modules-

      - run: docker-compose up -d

      - run: docker exec -i book-tatsujin-sql yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-node_modules-{{ checksum "package.json" }}

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: dockerize -wait tcp://localhost:3306-timeout 1m

      - run: docker exec -i book-tatsujin-sql yarn test

workflows:
  version: 2
  build:
    jobs:
      - build